### ISSUE TITLE
Add option to download experimental version, hardened version or sandboxed version 

### ISSUE THREAD

**Issue by GitHubPleaseDontBlockTor** [micahflee/torbrowser-launcher#258] opened 2016-12-22 09:41 UTC

**Comment by ge-fa** [comment] 2017-01-29 11:16
See #207 as well.

**Comment by jyn514** [comment] 2017-07-17 19:56
@GitHubPleaseDontBlockTor Is there a binary available for sandboxed-tor-browser? I looked at the [docs page](https://trac.torproject.org/projects/tor/wiki/doc/TorBrowser/Sandbox/Linux) and there's only a link to source, no executables. I doubt anyone wants the launcher to compile executables from source.

**Comment by davidbaumann** [comment] 2023-01-10 10:09
Duplicate of #207

**Closed by davidbaumann** 2023-01-10 10:09 UTC
