### ISSUE TITLE
how fix error tor browser on fedora 27 ?

### ISSUE THREAD

**Issue by sajjads24** [micahflee/torbrowser-launcher#309] opened 2018-01-26 09:34 UTC
hi
how fix error tor browser on fedora 27 after update to kernel 4.14.14 ?
i am can not run tor browser ...!?
`[sajjad@localhost ~]$ torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.8
https://github.com/micahflee/torbrowser-launcher
Refreshing local keyring...
Keyring refreshed successfully...
  No key updates for key: EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 62, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 91, in __init__
    if not self.common.settings['installed'] or not self.check_min_version():
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 603, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
IOError: [Errno 2] No such file or directory: '/home/sajjad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'
[sajjad@localhost ~]$ `

**Comment by bwitt** [comment] 2018-01-26 18:11
This sounds like a dupe of #306

**Comment by axvr** [comment] 2018-01-27 16:19
Yeah, this is the error caused by #306. I have the exact same same problem

**Closed** 2018-01-27 21:40 UTC
Labels: duplicate
