### ISSUE TITLE
Installing via "Tor Browser Launcher Settings" causes AttributeError (0.2.5)

### ISSUE THREAD

**Issue by torpet** [micahflee/torbrowser-launcher#241] opened 2016-07-12 14:33 UTC
https://gist.github.com/torpet/d3517e48edbde1cbbcdf907ae8e76de9

This error occurs when clicking "Save & Install".

System: Ubuntu 16.04

**Comment by h01ger** [comment] 2016-07-12 14:44
On Tue, Jul 12, 2016 at 07:33:12AM -0700, torpet wrote:
> `
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line 219, in install
>     self.save()
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line 240, in save
>     self.common.settings['force_en-US'] = self.force_en_checkbox.get_active()
> AttributeError: Settings instance has no attribute 'force_en_checkbox'
> `
> 
> System: Ubuntu 16.04

confirmed. that's also causing the test failures on
https://jenkins.debian.net/view/torbrowser/


-- 
cheers,
	Holger

**Comment by u451f** [comment] 2016-07-12 14:58
That's a duplicate of https://github.com/micahflee/torbrowser-launcher/issues/240

**Comment by h01ger** [comment] 2016-07-12 23:15
On Tue, Jul 12, 2016 at 07:33:12AM -0700, torpet wrote:
> `
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line 219, in install
>     self.save()
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line 240, in save
>     self.common.settings['force_en-US'] = self.force_en_checkbox.get_active()
> AttributeError: Settings instance has no attribute 'force_en_checkbox'

a way to reproduce under plain Debian:

unset LANG
torbrowser-launcher --settings

then click on "(re-)install Tor Browser" and it will go 

Traceback (most recent call last):
  File
"/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line
225, in reinstall
    self.save()
  File
"/usr/lib/python2.7/dist-packages/torbrowser_launcher/settings.py", line
240, in save
    self.common.settings['force_en-US'] =
self.force_en_checkbox.get_active()
AttributeError: Settings instance has no attribute 'force_en_checkbox'


if you set LANG="de_DE.UTF-8" and do the above, it works nicely, though
it claims to *always* re-download and install the browsers which I believe
is incorrect: it only verifies and unpacks an existing archive. (which
still shouldnt be done as it takes some time…)


-- 
cheers,
	Holger

**Comment by intrigeri** [comment] 2016-07-13 00:52
The fix should be easy: move the initialization of
`self.force_en_checkbox` to outside of the `if self.common.language !=
'en-US'`, and set it to non-active and hide it by default.

**Comment by h01ger** [comment] 2016-07-20 11:19
On Tue, Jul 12, 2016 at 05:52:43PM -0700, intrigeri wrote:
> The fix should be easy: move the initialization of
> `self.force_en_checkbox` to outside of the `if self.common.language !=
> 'en-US'`, and set it to non-active and hide it by default. 

ping?


-- 
cheers,
	Holger

**Comment by micahflee** [comment] 2016-07-22 20:05
Thanks for pinging me in person @h01ger :). I think https://github.com/micahflee/torbrowser-launcher/commit/8280e90b541b391bc2e61b71d528983af0bb45cc should fix it. Can you test?

**Closed** 2016-07-25 17:31 UTC
