### ISSUE TITLE
tor browser signature verification failed 

### ISSUE THREAD

**Issue by beer-to-code** [micahflee/torbrowser-launcher#354] opened 2018-09-17 16:12 UTC
![error](https://user-images.githubusercontent.com/37625966/45635398-7c803980-bac2-11e8-82ca-ec5394474182.jpg)

error code : GENERIC_VERIFY_FAIL

**Comment by DJKuhpisse** [comment] 2018-09-17 17:11
Same on Ubuntu bionic x64. Yesterday  installed it successfully on another Ubuntu bionic x64. Today certificate error, I tried different mirrors (yesterday dist.torproject.org worked)

**Comment by micahflee** [comment] 2018-09-17 17:37
Duplicate of #349. We can discuss it there.

**Closed by micahflee** 2018-09-17 17:37 UTC
Labels: duplicate
