### ISSUE TITLE
New 7.0 release not being updated to

### ISSUE THREAD

**Issue by nickjwhite** [micahflee/torbrowser-launcher#276] opened 2017-06-09 11:00 UTC
torbrowser-launcher is only picking up version 6.5.2, not the newest release, which is 7.0. This is a problem as torbrowser auto-updates itself when running, which causes it to stop launching the following time it starts up (maybe due to a signature check or something? nothing obvious appears in the console log).

The version_check_url in common.py is set to https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US, which is where the 6.5.2 comes from; https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions has 7.0 in there. But naively changing it doesn't work, I guess because they are not in the same format.

An alternative fix to updating the url (presuming the one torbrowser-launcher will be updated soon) would be to update the torbrowser configuration to not auto-update.

**Comment by JoaquinMVR** [comment] 2017-06-11 22:59
Same problem here.

**Comment by oapol** [comment] 2017-06-12 08:16
Same here. Can you tell me if have the downloaded tbb 7 tar.xz in ~/.cache/torbrowser/download? I don't and I am wondering if its the same for others.

**Comment by nickjwhite** [comment] 2017-06-12 14:18
The workaround that I'm using at the moment (to stay with 6.5.2), was to delete $HOME/.config/torbrowser, so that torbrowser-launcher re-downloads 6.5.2, then as soon as it opens navigate to about:config and switch app.update.enabled and app.update.auto to false, then quit and re-open it. That way at least 7.0 won't be downloaded, then non-open-able.

**Comment by oapol** [comment] 2017-06-12 18:54
Thank  you. Can you also answer about the tbb 7 file in that directory?

**Comment by HighCommander4** [comment] 2017-06-14 07:19
This has gotten even worse, as it appears the 6.5.2 release was removed from https://dist.torproject.org/torbrowser/ (e.g. the launcher tries to download https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux64-6.5.2_en-US.tar.xz.asc which doesn't resolve), so the described workaround doesn't work either.

**Comment by u451f** [comment] 2017-06-16 14:46
Confirmed and also reported on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864733

**Comment by intrigeri** [comment] 2017-06-16 17:54
Besides, for users with AppArmor enabled, at least some bits of https://github.com/micahflee/torbrowser-launcher/pull/277 will be needed.

**Comment by boklm** [comment] 2017-06-16 23:48
This should be fixed now.

The reason was that Tor Browser has been changing the URL of its update manifests, but torbrowser-launcher was still using the old one. I added a redirect from the old URL to the new one, so this should be working again.

And I opened a pull request to use the new URL:
https://github.com/micahflee/torbrowser-launcher/pull/279

**Comment by micahflee** [comment] 2017-06-20 21:36
@boklm thanks! Sorry about letting this issue go for so long. I've been traveling without access to my computer. I'll review your PR now.

**Closed** 2017-06-21 00:46 UTC
