### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by dancris75** [micahflee/torbrowser-launcher#350] opened 2018-09-13 01:06 UTC
By trying to install tor on my laptop with Lubuntu 18.04 system i repeatedly get this error message:

SIGNATURE VERIFICATION FAILED!
Error Code: GENERIC_VERIFY_FAIL

can someone help me to solve the problem?

**Comment by micahflee** [comment] 2018-09-14 18:34
This is a duplicate of #349

**Closed by micahflee** 2018-09-14 18:34 UTC
Labels: duplicate
