### ISSUE TITLE
error code: GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by algreen702021** [micahflee/torbrowser-launcher#645] opened 2022-07-23 16:17 UTC
Can't verify signature on Ubuntu 18.04
regards
AL

**Comment by John-Wilson-Redcar** [comment] 2022-08-09 20:01
Same problem on various distros..
![Screenshot_2022-08-09_21-00-04](https://user-images.githubusercontent.com/110937041/183750172-9a61a0fd-ef49-420c-bd54-84912174b891.png)

**Comment by ahs9** [comment] 2022-09-05 15:58
roger that

**Comment by Bill-Overman** [comment] 2022-09-14 22:34
Same Issue as John-Wilson-Re...

Running Linux Mint 19.2
Python was pre-installed for other purposes.

**Comment by danmcne** [comment] 2022-10-04 09:39
Same issue

SIGNATURE VERIFICATION FAILED!
Error Code: GENERIC_VERIFY_FAIL

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.



Refreshing the keyring doesn't seem to help

**Comment by davidbaumann** [comment] 2022-12-24 09:16
Duplicate of #633

**Closed by davidbaumann** 2022-12-24 09:16 UTC
