### ISSUE TITLE
server indicates a failure, alternative key servers  

### ISSUE THREAD

**Issue by shirishag75** [micahflee/torbrowser-launcher#305] opened 2018-01-09 07:32 UTC
I have been trying unsuccessfully for last half hour or so to get torbrowsr-launched. 

```
$ torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.8
https://github.com/micahflee/torbrowser-launcher
Refreshing local keyring...
^CTraceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 54, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 80, in __init__
    self.init_gnupg()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 208, in init_gnupg
    self.import_keys()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 296, in import_keys
    self.refresh_keyring()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 222, in refresh_keyring
    p.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

```

It was basically stopping at refreshing the localkeyring with the server. 

I then tried the option shared -

```
$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: keyserver refresh failed: Server indicated a failure
```

There should be alternative keyservers that we should be able to use in case the main one doesn't work.

**Comment by baptx** [comment] 2018-01-28 22:57
Thanks for sharing the gpg command, it solved the "SIGNATURE VERIFICATION FAILED!" error messages indicating that I might be under attack.
I got this error message when I removed my `.local/share/torbrowser`.
I removed this folder because I got an error when starting torbrowser-launcher.
Now the error is back again. I don't know if it is related to this issue but you may have an idea (I will create another issue if needed).

Here is the console output:
> bapt@dell:~$ torbrowser-launcher 
> Tor Browser Launcher
> By Micah Lee, licensed under MIT
> version 0.2.4
> https://github.com/micahflee/torbrowser-launcher
> Traceback (most recent call last):
>   File "/usr/bin/torbrowser-launcher", line 30, in <module>
>     torbrowser_launcher.main()
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main
>     app = Launcher(common, url_list)
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 94, in __init__
>     self.run(False)
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
>     if not self.check_min_version():
>   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
>     for line in open(self.common.paths['tbb']['versions']).readlines():
> IOError: [Errno 2] No such file or directory: '/home/bapt/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

**Comment by u451f** [comment] 2018-01-29 13:56
Yes, this sounds like a duplicate of #306.

**Comment by micahflee** [comment] 2018-03-22 16:51
Yup, and #306 is resolved now.

**Closed by micahflee** 2018-03-22 16:51 UTC
