### ISSUE TITLE
typeerror on gentoo

### ISSUE THREAD

**Issue by navtis** [micahflee/torbrowser-launcher#613] opened 2021-11-27 23:19 UTC
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.9/site-packages/torbrowser_launcher/__init__.py", line 76, in main
    common = Common(tor_browser_launcher_version)
  File "/usr/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 66, in __init__
    self.load_settings()
  File "/usr/lib/python3.9/site-packages/torbrowser_launcher/common.py", line 432, in load_settings
    self.settings = pickle.load(open(self.paths["settings_file_pickle"]))
TypeError: a bytes-like object is required, not 'str'

**Comment by davidbaumann** [comment] 2023-01-10 09:41
Duplicate of #389

**Closed by davidbaumann** 2023-01-10 09:41 UTC
