### ISSUE TITLE
Initial use: SIGNATURE VERIFICATION FAILED (no error code)

### ISSUE THREAD

**Issue by GNUbahn** [micahflee/torbrowser-launcher#382] opened 2019-01-03 20:24 UTC
On a fresh install of Trisquel 8.0, Tor Browser Launcher downloads Tor Browser without problems but signature verification gives me: SIGNATURE VERIFICATION FAILED

I was presented with no error code. See the attached pic.

![signature verification failed](https://user-images.githubusercontent.com/22903560/50659755-c3c10600-0f9d-11e9-87ae-b7b9c0721d5a.png)

**Comment by GNUbahn** [comment] 2019-01-04 11:47
Thanks for your comment, traumschule. 

First, I was about to post my issue under one of the others but realised that there was one difference: I did not get an error code, as they did. That's why I made a new issue, rather than commenting one already established. I am not confident that I did the right thing, I just wanted to provide the additional information.

Secondly, I am aware of the signing key problem. Do you have any idea about when it will be solved?

**Comment by GNUbahn** [comment] 2019-01-04 11:54
OT: @traumschule, I just read about Traumschule Riebau. It looks interesting.  But why the name Traumschule?

**Comment by traumschule** [comment] 2019-01-04 12:59
I have no idea, @micahflee isn't answering my mails since some months either. Is probably quite busy with the intercept, sadly pretty much a fail for tb-launcher though. Either someday they transfer privileges or someone else with enough credibility maintains a fork. AFAIK The Torrotect has no interest in doing so at the moment.

> OT: @traumschule, I just read about Traumschule Riebau. It looks interesting. But why the name Traumschule?

This place is about learning without formal hierarchies or putting force on others.

**Comment by micahflee** [comment] 2019-01-04 23:50
Sorry about not answering your emails @traumschule ! This "signature verification failed" bug was fixed and released in October 2018 with version 0.3.1.

The problem is that occasionally an update on Tor Browser's side breaks Tor Browser Launcher, and then once it's fixed, the fix takes a very long time to make it into package repositories. For example, Trisquel 8.0 includes torbrowser-launcher 0.2.4, from March 2016. But if you install torbrowser-launcher in Debian Buster (which includes version 0.3.1) it works fine without a verification error.

It will probably working if you install torbrowser-launcher [from the PPA](https://github.com/micahflee/torbrowser-launcher#installing-in-ubuntu), or if you [build it from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md).

**Closed by micahflee** 2019-01-04 23:50 UTC

**Comment by traumschule** [comment] 2019-01-05 09:42
No worries, and welcome back :)

Upstream is aware of the issue now:
https://trac.torproject.org/projects/tor/ticket/28971
> It looks like the master signing key (not just the subkey) is due to expire in 20 months. So we are on track for another surprise for all the various distros and packages that try to automate checking the signature.

**Comment by GNUbahn** [comment] 2019-01-05 14:03
@micahflee, I was using your PPA (I actually didn't know it was in the Trisquel repo).

**Comment by GNUbahn** [comment] 2019-01-05 14:07
@traumschule, it sounds like a nice place you have there. If I ever come nearby...
