### ISSUE TITLE
Failed on first launch F21

### ISSUE THREAD

**Issue by ToBeReplaced** [micahflee/torbrowser-launcher#174] opened 2015-03-06 18:36 UTC
True of both 0.1.9-2 and 0.1.7-1 on F21.

The verify command fails.

````
$ gpg --homedir ~/.local/share/torbrowser/gnupg_homedir/ --verify ~/.cache/torbrowser/download/sha256sums.txt.asc
gpg: assuming signed data in `/home/example/.cache/torbrowser/download/sha256sums.txt
gpg: Signature made Wed 25 Feb 2015 12:58:21 AM MST using RSA key ID F65C2036
gpg: BAD signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
````

Am I missing an installation step? What is the genuine signature? I have publics for 'Tor Browser Developers (signing key)' and 'Erinn Clark' in the gnupg_homedir.
````

**Comment by code4guid** [comment] 2015-03-08 16:06
I have this same issues. 

Fedora release 21 (Twenty One)
torbrowser-launcher 0.1.9-1 (from [github], and from some repo this same result)

**Comment by micahflee** [comment] 2015-05-11 21:19
This is a duplicate of #159

**Closed by micahflee** 2015-05-11 21:19 UTC
