### ISSUE TITLE
Feature Request: run in command line with all default setting (mainly for CI, a.k.a. continuous integration)

### ISSUE THREAD

**Issue by rogers0** [micahflee/torbrowser-launcher#414] opened 2019-08-21 18:03 UTC
Request to run in command line for CI purpose.
It's okay to just download the latest TBB, without really running it.
If it's already latest, simply exit 0.

Maybe related to #314

**Comment by davidbaumann** [comment] 2023-01-04 07:47
Duplicate of #39

**Closed by davidbaumann** 2023-01-04 07:47 UTC
