### ISSUE TITLE
Erorr on Ubuntu 20.04

### ISSUE THREAD

**Issue by PLMBakery** [micahflee/torbrowser-launcher#667] opened 2022-12-22 13:33 UTC
brings up error 404

**Comment by ozgurYavuz** [comment] 2022-12-23 15:43
I had the same issue on Ubuntu 22.10
I solved it by editing the "common.py" library file
The file was in "/usr/lib/python3/dist-packages/torbrowser_launcher/" for my case
The modifications done are:
from
`            tarball_filename = (
                "tor-browser-" + arch + "-" + tbb_version + "_" + language + ".tar.xz"`
to
`            tarball_filename = (
                "tor-browser-" + arch + "-" + tbb_version + "_" + "ALL" + ".tar.xz"`
basically setting the language to "ALL" instead of "en_US"

and
from
`                "tbb": {
                    "changelog": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser_"
                    + language
                    + "/Browser/TorBrowser/Docs/ChangeLog.txt",
                    "dir": tbb_local + "/tbb/" + self.architecture,
                    "dir_tbb": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser_"
                    + language,
                    "start": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser_"
                    + language
                    + "/start-tor-browser.desktop",
                }`
to
`                "tbb": {
                    "changelog": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser"    #   <-
                    + "/Browser/TorBrowser/Docs/ChangeLog.txt",
                    "dir": tbb_local + "/tbb/" + self.architecture,
                    "dir_tbb": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser",   #   <-
                    "start": tbb_local
                    + "/tbb/"
                    + self.architecture
                    + "/tor-browser"
                    + "/start-tor-browser.desktop",
                }`
basically replacing every instance of " + "/tor-browser_" + language " to " + "/tor-browser" "

**Comment by davidbaumann** [comment] 2022-12-23 20:24
Duplicate of #659

**Closed by davidbaumann** 2022-12-23 20:24 UTC
