### ISSUE TITLE
Crashes on debian testing

### ISSUE THREAD

**Issue by zarniwoop123** [micahflee/torbrowser-launcher#197] opened 2015-09-13 01:48 UTC
torbrowser-launcher crashes on debian testing. I've included the error log below.

Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 33, in <module>
    from launcher import Launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 31, in <module>
    from twisted.web.client import Agent, RedirectAgent, ResponseDone, ResponseFailed
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 767, in <module>
    from twisted.internet.ssl import (CertificateOptions,
  File "/usr/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 223, in <module>
    from twisted.internet._sslverify import (
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 192, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation(OpenSSL)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 167, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/usr/lib/python2.7/dist-packages/service_identity/__init__.py", line 12, in <module>
    from . import pyopenssl
  File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
    from ._common import (
  File "/usr/lib/python2.7/dist-packages/service_identity/_common.py", line 136, in <module>
    @attributes(["pattern"], apply_with_init=False)
TypeError: attributes() got an unexpected keyword argument 'apply_with_init'

**Comment by micahflee** [comment] 2015-11-06 05:24
Just tested this in debian testing, and I can't reproduce. Whatever the problem was I think it's fixed now.

**Closed by micahflee** 2015-11-06 05:24 UTC
