### ISSUE TITLE
Error Code. Pop! OS v 20.10

### ISSUE THREAD

**Issue by MotherOfPerls** [micahflee/torbrowser-launcher#544] opened 2020-12-22 23:55 UTC
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key Expired
If the message persists report the above error

**Comment by Gladox114** [comment] 2020-12-23 16:52
Maybe it's way less secure but because of that error I installed the .deb version in the pop_shop which worked but maybe not that isolated like a flatpak. Not sure if this is important.

**Comment by AsciiWolf** [comment] 2020-12-23 21:10
Same issue as #543.

**Comment by AsciiWolf** [comment] 2020-12-23 21:16
@MotherOfPerls Do you use a Flatpak Tor Browser Launcher or a regular deb one?

**Comment by MotherOfPerls** [comment] 2020-12-24 04:46
I fixed the issue. Instead of downloading it from the pop shop (package manager), I just downloaded it from the website and it worked fine lol.

**Comment by jtagcat** [comment] 2020-12-25 02:50
Duplicate of #534

**Closed** 2022-12-24 09:45 UTC
