### ISSUE TITLE
exceptions.OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by HighCommander4** [micahflee/torbrowser-launcher#178] opened 2015-05-04 21:34 UTC
I'm on Kubuntu 14.04. I installed torbrowser-launcher as instructed:

```
sudo add-apt-repository ppa:micahflee/ppa
sudo apt-get update
sudo apt-get install torbrowser-launcher
```

And then tried to run it, but I got the following error:

```
nr:~$ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Creating GnuPG homedir /home/nr/.local/share/torbrowser/gnupg_homedir
Importing keys
gpg: keyring `/home/nr/.local/share/torbrowser/gnupg_homedir/secring.gpg' created
gpg: keyring `/home/nr/.local/share/torbrowser/gnupg_homedir/pubring.gpg' created
gpg: /home/nr/.local/share/torbrowser/gnupg_homedir/trustdb.gpg: trustdb created
gpg: key 63FEE659: public key "Erinn Clark <erinn@torproject.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: key 93298290: public key "Tor Browser Developers (signing key) <torbrowser@torproject.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: no ultimately trusted keys found
Starting launcher dialog
LATEST VERSION 0
Checking for update
/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py:282: GtkWarning: Theme file for default has no directories

  self.window.show()
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Finished receiving body: Response body fully received
Running task: attempt_update
Checking to see if update is needed
TBB is not installed, attempting to install 4.5
Running task: download_sha256
Downloading https://dist.torproject.org/torbrowser/4.5/sha256sums.txt
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_sha256_sig
Downloading https://dist.torproject.org/torbrowser/4.5/sha256sums.txt.asc
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_tarball
Downloading https://dist.torproject.org/torbrowser/4.5/tor-browser-linux64-4.5_en-US.tar.xz
Updating over Tor
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: Signature made Mon 27 Apr 2015 07:46:17 AM CDT using RSA key ID D40814E0
gpg: Good signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: BA1E E421 BBB4 5263 180E  1FC7 2E1A C68E D408 14E0
Running task: extract
Extracting tor-browser-linux64-4.5_en-US.tar.xz
Running task: run
Running /home/nr/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1462, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1511, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1499, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 532, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1154, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 378, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 395, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 332, in run_task
    self.verify()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 565, in verify
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 336, in run_task
    self.extract()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 609, in extract
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 340, in run_task
    self.run()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 640, in run
    subprocess.call([self.common.paths['tbb']['start']])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
exceptions.OSError: [Errno 2] No such file or directory
```

What is going wrong?

**Comment by ovitech** [comment] 2015-05-08 00:07
Yup, I'm getting similar errors on 2 Linux laptops: one with Linux Mint 17.1 MATE and one with Ubuntu Gnome 14.0.2. same error received after a fresh install, kernel 3.16.0-37:

$ torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.5
Checked for update within 24 hours, skipping
TBB is not installed, attempting to install 4.5
Running task: download_sha256
Downloading https://dist.torproject.org/torbrowser/4.5/sha256sums.txt
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_sha256_sig
Downloading https://dist.torproject.org/torbrowser/4.5/sha256sums.txt.asc
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_tarball
Downloading https://dist.torproject.org/torbrowser/4.5/tor-browser-linux64-4.5_en-US.tar.xz
Updating over Tor
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: Signature made Mon 27 Apr 2015 13:46:17 IST using RSA key ID D40814E0
gpg: Good signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: BA1E E421 BBB4 5263 180E  1FC7 2E1A C68E D408 14E0
Running task: extract
Extracting tor-browser-linux64-4.5_en-US.tar.xz
Running task: run
Running /home/ot/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1462, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1511, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1499, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 532, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 911, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1154, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 378, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 395, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 332, in run_task
    self.verify()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 565, in verify
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 336, in run_task
    self.extract()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 609, in extract
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 340, in run_task
    self.run()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 640, in run
    subprocess.call([self.common.paths['tbb']['start']])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
exceptions.OSError: [Errno 2] No such file or directory

**Comment by micahflee** [comment] 2015-05-11 20:39
This is actually a duplicate of #176

**Closed by micahflee** 2015-05-11 20:39 UTC
Labels: bug
