### ISSUE TITLE
Missing Twisted dependency

### ISSUE THREAD

**Issue by pde** [micahflee/torbrowser-launcher#204] opened 2015-11-06 17:46 UTC
My long-running copy of torbrowser-launch recently stopped working (404 after wanting to update from tbb 5.0.3 to a 5.5 hardened copy, along with funny messages about mirrors).

After building the latest version from git, I get this:

```
pde@damoclid:~$ torbrowser-launcher 
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 33, in <module>
    from launcher import Launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 33, in <module>
    from twisted.web.iweb import IPolicyForHTTPS
ImportError: cannot import name IPolicyForHTTPS
```

**Comment by pde** [comment] 2015-11-06 17:46
```
dpkg -l python-twisted-web
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-===================================
ii  python-twisted- 13.2.0-1     all          HTTP protocol implementation togeth
```

**Comment by pde** [comment] 2015-11-06 17:49
After updating python-twisted-web, the launcher runs but I get an error about signature checks failing (maybe I'm under attack, it says) and then:
```
torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.1
https://github.com/micahflee/torbrowser-launcher
Updating over Tor
Checked for update within 24 hours, skipping
Verifying signature
Starting download over again
Downloading https://dist.torproject.org/torbrowser/5.5a4-hardened/tor-browser-linux64-5.5a4-hardened_en-US.tar.xz
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 313, in start
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 358, in run_task
    self.start_over()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 644, in start_over
    self.start(None)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 313, in start
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 342, in run_task
    self.download('tarball', self.common.paths['tarball_url'], self.common.paths['tarball_file'])
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 485, in download
    None)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1926, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 1557, in request
    parsedURI = URI.fromBytes(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/client.py", line 606, in fromBytes
    scheme, netloc, path, params, query, fragment = http.urlparse(uri)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 160, in urlparse
    raise TypeError("url must be bytes, not unicode")
TypeError: url must be bytes, not unicode
```

**Comment by pde** [comment] 2015-11-06 17:59
(I guess that's another bug)

**Comment by micahflee** [comment] 2015-11-06 18:03
Yesterday Tor released a hardened version of Tor Browser:
https://blog.torproject.org/blog/tor-browser-55a4-hardened-released

And they changed their `RecommendedTBBVersions` file to include it:
https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions

So now Tor Browser Launcher gets confused with the new format and thinks that `5.5a4-hardened-Linux` is the latest stable version, rather than `5.0.4-Linux`. I just fixed this and made a release last night. Specifically, this commit now checks the "release" channel XML file for the current version, which should be we more stable than `RecommendedTBBVersions`: https://github.com/boklm/torbrowser-launcher/commit/e07beac325b7bd716b7a053dcd5664c113e67458

Version 0.2.1 isn't in Debian yet, but you can fix it by building it from source.

**Comment by micahflee** [comment] 2015-11-06 18:04
Oh wait, it looks like you did update...

**Comment by micahflee** [comment] 2015-11-06 18:06
What's in your `~/.config/torbrowser/settings.json`? I bet you can edit that file and changed `latest_version` to `5.0.4` and then re-run it, and it will fix itself.

But I wonder where that unicode error came from. I'll take a look.

**Comment by micahflee** [comment] 2015-11-06 18:09
I'll say this is a duplicate of #205.

**Closed by micahflee** 2015-11-06 18:09 UTC
Labels: bug, duplicate

**Comment by pde** [comment] 2015-11-06 18:11
cat ~/.config/torbrowser/settings.json
{"accept_links": false, "modem_sound": false, "latest_version": "5.5a4-hardened", "installed_version": "5.0.4", "check_for_updates": false, "mirror": "https://dist.torproject.org/", "tbl_version": "0.2.1", "update_over_tor": true, "last_update_check_timestamp": 1446830854}

**Comment by molenick** [comment] 2015-11-24 08:59
I'm also experiencing the original reported problem.  I had installed torbrowser-launcher via apt-get, but I've removed that, built from source and am still getting the same error.  The torbrowser-launcher deb is is labeled torbrowser-launcher_0.2.2-1_all.deb.

I'm not sure if there's anything else I need to do, like manually update twisted_web.
