### ISSUE TITLE
torbrowser-launcher does not run ubuntu 22.04

### ISSUE THREAD

**Issue by NoLandMen496** [micahflee/torbrowser-launcher#628] opened 2022-03-09 15:21 UTC
Hi. I know I am using a daily build of ubuntu 22.04, but is there any way to solve the issue? The code:

```bash
torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.3
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US

Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py", line 98, in main
    gui.move(
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
```

**Comment by timoa** [comment] 2022-04-24 08:21
Same issue with the official Ubuntu 22.04 LTS, released on the 21st April 2022.

The shortcuts on menu and desktop are created, but it is not able to download the latest Tor Browser release.

The install crashed every time We launch Tor Browser Launch with same error.

**Comment by XaverStiensmeier** [comment] 2022-04-27 09:15
I fixed this by changing:
```
    gui.move(
                (desktop.width() - window_size.width()) / 2,
                (desktop.height() - window_size.height()) / 2
            )
```

To:

```
    gui.move(
                int((desktop.width() - window_size.width()) / 2),
                int((desktop.height() - window_size.height()) / 2)
            )
```
I am not sure whether this has other effects than fixing the minor bug.

**Comment by Am0rphous** [comment] 2022-05-10 12:49
Same on Kali Linux:

Kernel:           5.8.0-kali3-amd64
Release:        2022.2
Codename:    kali-rolling

**Comment by teward** [comment] 2022-06-22 21:14
All: This is a Python 3.10 issue introduced by heavier strictness - see #599 - it's the same issue regardless of the distro in use

**Comment by j2l** [comment] 2022-07-28 06:52
I guess it's fixed because it's closed, but 0.3.3.6 is still the installable deb package and it fails to run.
Hope it will be updated soon.
Have a great day!

**Comment by lazytownfan** [comment] 2022-07-31 02:18
According to this Q&A from [Ask Ubuntu](https://askubuntu.com/questions/1404606/tor-browser-not-launching-on-ubuntu-22-04), the location of the `__init__.py` file is at `/usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py` - in case you haven't been able to find this info by looking at only GitHub comments.

I think I will try to report this directly on Ubuntu Launchpad, as this is affecting me on Pop!\_OS 22.04.  However, this issue doesn't occur on Debian Sid, which is on version `0.3.5-3` and doesn't experience this issue.  (The [bug tracker](https://launchpad.net/ubuntu/+source/torbrowser-launcher/+bugs) hasn't seen any activity since 2019.)

For whatever reason, Ubuntu's packaging of `torbrowser-launcher` lags behind upstream Debian Sid (even for the latest, non-LTS releases of Ubuntu).  Even the upcoming release [Kinetic](https://packages.ubuntu.com/kinetic/torbrowser-launcher) is still on `0.3.3-6ubuntu1`.

You may compare [Jammy](https://packages.ubuntu.com/jammy/torbrowser-launcher) with [Debian Sid](https://packages.debian.org/source/unstable/torbrowser-launcher).  Also, you can compare Ubuntu's [changelog](https://changelogs.ubuntu.com/changelogs/pool/universe/t/torbrowser-launcher/torbrowser-launcher_0.3.3-6ubuntu1/changelog) with the GitHub [release tags](https://github.com/micahflee/torbrowser-launcher/tags).

**Comment by Flashwalker** [comment] 2022-08-02 17:09
The same fail, 22.04, python 3.10
Even if set python to 3.9:
`sudo update-alternatives --config python`

**Comment by icceland** [comment] 2022-08-06 01:35
Open as root file
**/usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py**

At the end of the file (lines 98 - 101) locate:
```
            gui.move(
                (desktop.width() - window_size.width()) / 2,
                (desktop.height() - window_size.height()) / 2
            )
```
Edit it to:
```
            gui.move(
                (desktop.width() - window_size.width()) // 2,
                (desktop.height() - window_size.height()) // 2
            )
```
As you see, the difference is replacing **/** with **//**.

Done.

**Comment by Am0rphous** [comment] 2022-08-07 13:11
Awesome, thanks @icceland !
I can confirm that this made it work on 22.04.

Did you make a pull request?

**Comment by icceland** [comment] 2022-08-07 20:26
Thanks for your kind answer .
I'm honestly glad to be somehow helpful. I'm barely familiar with github procedures. It would be generous if you could do this for me and of course all thees other users out there.
Fell free to do it for me. Can we count with you?
Kind regards!

> Awesome, thanks @icceland ! I can confirm that this made it work on 22.04.
> 
> Did you make a pull request?

**Comment by teward** [comment] 2022-08-07 21:11
> Thanks for your kind answer @Am0rphous . I'm honestly glad to be somehow helpful. I'm barely familiar with github structure and out of time to learn it at the moment. It would be generous if you could do this for me and all thees other users out there. Feel free to do it for me. Can we count with you? Kind regards!
> 
> > Awesome, thanks @icceland ! I can confirm that this made it work on 22.04.
> > Did you make a pull request?

I was already prepping a patch that I can SRU into Ubuntu's packaging.  I can adapt it to a PR and give you credit in the commit message @icceland.

**Comment by teward** [comment] 2022-08-07 21:16
@icceland and others: Pull request made (see #646) using the code as stated here by icceland modified into the init file as based here in the code (which is `${GIT_ROOT}/torbrowser_launcher/__init__.py`)

**Comment by Am0rphous** [comment] 2022-08-08 11:28
Seems @teward was a bit faster then me @icceland :D 

Thanks to both of you!! 🥇🥇

**Comment by lazytownfan** [comment] 2022-09-04 07:54
The [bug fix](https://bugs.launchpad.net/ubuntu/+source/torbrowser-launcher/+bug/1963286) by @teward for Ubuntu's packaging will likely be processed in at least 1 week before PR #646 is accepted here on GitHub.

**Comment by siriusstar2007** [comment] 2022-09-10 23:56
Hello,

How do I open the file _init_.py to modify it?

Thank you!

**Comment by siriusstar2007** [comment] 2022-09-11 01:08
I managed to open the _init_.py file with the Qt Creator application but I can't save the changes I made because I don't have the permission.
Should I open the _init_.py file in root mode and if so, how should I do?

Thanks a lot!

**Comment by Am0rphous** [comment] 2022-09-12 07:58
@siriusstar2007 Yes, use e.g. nano.
_sudo nano /name/my/file_

**Comment by teward** [comment] 2022-09-12 15:03
FYI in Ubuntu 22.04 this has been fixed with my patch and an SRU.

**Comment by micahflee** [comment] 2022-12-13 02:28
Fixed in https://github.com/micahflee/torbrowser-launcher/commit/8c69da13a7230695a0cb406e9638b301529d2ff4

**Closed by micahflee** 2022-12-13 02:28 UTC
