### ISSUE TITLE
AppArmor profiles broken with TBB 4.5+

### ISSUE THREAD

**Issue by micahflee** [micahflee/torbrowser-launcher#181] opened 2015-05-15 22:26 UTC
I've started to take a stab at fixing them myself, but I can tell I'm not doing the best job. Now `usr.bin.torbrowser-launcher` needs to execute `start-tor-browser.desktop`, which itself executes `Browser/start-tor-browser`. But it looks like the start-tor-browser script has changed a bunch, and needs to execute `Browser/execdesktop` and possibly other stuff.

We could create new AppArmor profiles, or try to incorporate the new binaries into existing ones. @intrigeri would you be willing to update them?

**Comment by intrigeri** [comment] 2015-05-19 09:27
Micah Lee wrote (15 May 2015 22:26:57 GMT) :
> I've started to take a stab at fixing them myself, but I can tell I'm not doing the
> best job. Now `usr.bin.torbrowser-launcher` needs to execute
> `start-tor-browser.desktop`, which itself executes `Browser/start-tor-browser`.
> But it looks like the start-tor-browser script has changed a bunch, and needs to
> execute `Browser/execdesktop` and possibly other stuff.

> We could create new AppArmor profiles, or try to incorporate the new binaries into
> existing ones. @intrigeri would you be willing to update them?

My current take on this is that we should go on confining the actual
browser and tor processes, and possibly torbrowser-launcher, but give
up with confining start-tor-browser: its attack surface is small,
which IMO doesn't make it worth constantly adapting to changes in its
behaviour and breaking TBL when Tor Browser is upgraded but our stuff
is lagging behind.

**Comment by micahflee** [comment] 2015-05-19 20:06
@intrigeri I agree we should give up on confining start-tor-browser. I just made a commit https://github.com/micahflee/torbrowser-launcher/commit/39901c6ddc05bb96f2d14cebefec515c2009a222 that I believe fixes this issue. Can you confirm?

**Comment by intrigeri** [comment] 2015-05-22 15:23
Micah Lee wrote (19 May 2015 20:06:52 GMT) :
> @intrigeri I agree we should give up on confining start-tor-browser. I just made
> a commit
> https://github.com/micahflee/torbrowser-launcher/commit/39901c6ddc05bb96f2d14cebefec515c2009a222
> that I believe fixes this issue. Can you confirm?

Untested, but yeah, it looks good! Thanks :)

Note that such reviews would be easier if you did atomic commits, and
documented all changes in the commit message :)

E.g.:

<pre>
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/TorBrowser/,}Data/Browser/profiles.ini r,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/TorBrowser/,}Data/Browser/profile.default/ r,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/TorBrowser/,}Data/Browser/profile.default/** rwk,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/TorBrowser/,}Tor/tor Px,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/,}Desktop/ rw,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/,}Desktop/** rwk,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/,}Downloads/ rw,
-  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/,}Downloads/** rwk,
[...]
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Data/Browser/profiles.ini r,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Data/Browser/profile.default/ r,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Data/Browser/profile.default/** rwk,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Tor/tor Px,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/Desktop/ rw,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/Desktop/** rwk,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/Downloads/ rw,
+  owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/Downloads/** rwk,
</pre>

... has nothing to do with the changes documented by the corresponding
commit message. And the main change that is documented by "and fix
profiles to work with TBB 4.5+" is a one-line addition, that's kinda
hidden in the middle of these unrelated ones. See what I mean? :)

Also, regarding:

	owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Tor/libstdc++.so.6 m,

I would suggest something more future proof, like:

	owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Tor/*.so.[0-9] m,

While I'm at it, regarding
https://github.com/micahflee/torbrowser-launcher/commit/da486003205ddb4c6d3cdc2609310b36bec6b124,
perhaps it would be nice to keep supporting the previous OnionShare
directories, to ensure a smoother upgrade path for people who e.g.
upgrade TBL first, and OnionShare later?

Cheers!

**Comment by rufoa** [comment] 2015-05-22 16:44
Confirmed working on debian stretch

One minor issue:

The "Launch Tor Browser" button in the settings window doesn't work because it gets caught by apparmor:
```apparmor="DENIED" operation="exec" profile="/usr/bin/torbrowser-launcher" name="/usr/bin/torbrowser-launcher"```

Changing the confinement mode of /usr/bin/torbrowser-launcher to "rix" fixes the issue, but I'm not familiar enough with apparmor to say whether this is the best solution.

**Comment by intrigeri** [comment] 2015-08-12 08:18
Tor Browser 5.0 loads more shared libraries than `libstdc++6` from the `Browser/TorBrowser/Tor` directory, so we need something like:

`owner @{HOME}/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/TorBrowser/Tor/*.so{,.[0-9]*} mr,`

**Comment by intrigeri** [comment] 2015-08-12 09:31
For the record, I've uploaded 0.2.0-2 to Debian, that adds the above line and puts `usr.bin.torbrowser-launcher` and `torbrowser.start-tor-browser` to complain mode.

**Comment by nopjmp** [comment] 2015-08-13 04:22
Also, I found playing sounds (possibly video haven't tested) requires more permissions to things like /dev/shm (looks like session files) and /usr/bin/pulseaudio. I'm running on Debian 8 with Gnome 3. I would more than happy to test out any recommendations and provide feedback.

@intrigeri the shared library rule fixed my initial loading problem on 5.0. Thanks!

**Comment by h01ger** [comment] 2016-03-06 15:50
Can someone please test 0.2.3-1 on Ubuntu and report back whether the apparmor profiles work now?

**Comment by TomAshley303** [comment] 2016-03-10 21:47
Is this thing stable enough to use on wily?

**Comment by h01ger** [comment] 2016-05-14 23:01
I recommend to close this bug: apparmor works fine on Debian, nobody commented here and also there aint any new apparmor related torbrowser-launcher bug on launchpad. plus: reopening a new bug if things are still broken is easy - but it looks like it works now! :)

I just cannot close this bug myself :(

**Comment by intrigeri** [comment] 2016-05-15 08:03
Holger Levsen wrote (14 May 2016 23:02:00 GMT) :
> I recommend to close this bug: apparmor works fine on Debian,

Does it? FTR, I am still incrementally (every 6 weeks ;) improving `torbrowser.Browser.firefox` locally, and will propose a pull request once it really works for me, that is once it doesn't break Tor Browser's auto-upgrader (I am not going to file a new bug report every 6 weeks for the next iteration). But this can happen on a new bug report :)

**Comment by h01ger** [comment] 2016-05-15 10:17
Intrigeri, there is no Debian bug open about apparmor upgrade problems, so I've been under the assumption that there is no problem.

And in any case, this bug report is not helpful so I recommend to still close it.

**Comment by intrigeri** [comment] 2016-05-15 21:21
> Intrigeri, there is no Debian bug open about apparmor upgrade problems, so I've been under the assumption that there is no problem.

Last time I filed such a bug report and attached a patch that (as I thought I made clear back then) was probably not enough to fix the problem yet, and needed more tests, the bug was closed by an upload that contained that incomplete patch. And indeed, experience showed that it was not sufficient to make the whole thing work. I lack time+energy+motivation to argue about how bugs in this Debian package should be handled ("aggressive" closing vs. confirming that the problem is really gone). So I took it easy, gave up trying to keep the Debian BTS up-to-date on this topic, and focused on trying to get something that really works for me, that I can send directly upstream at some point. My hope is that it'll save everyone some boring paperwork, allow me to keep contributing to fixing this problem in a relaxed way that I'm comfortable with, and result in something that improves the actual TBL + AppArmor user experience at some point.

> And in any case, this bug report is not helpful so I recommend to still close it.

Absolutely! :)

**Comment by h01ger** [comment] 2016-05-16 10:49
FWIW, I closed this bug with the upload as I believed it was fixed. That's a rather common best practice.

**Comment by intrigeri** [comment] 2016-05-16 17:19
> FWIW, I closed this bug with the upload as I believed it was fixed. That's a rather common best practice.

That's precisely the kind of discussions I didn't want to get into, so I'll stop here :)

**Comment by intrigeri** [comment] 2017-09-08 06:38
The issue this bug was about originally has been fixed, please close.

**Comment by ageis** [comment] 2018-02-27 05:16
Can be closed.

**Comment by ageis** [comment] 2018-02-27 05:37
Closing per previous comment.

**Closed by ageis** 2018-02-27 05:37 UTC
Labels: apparmor, bug
