### ISSUE TITLE
browser launcher and cannot update chrome or access downloads

### ISSUE THREAD

**Issue by DrFame** [micahflee/torbrowser-launcher#622] opened 2022-02-04 13:59 UTC
ES3D989A9E2D47BF

**Comment by u451f** [comment] 2022-04-25 18:51
See https://github.com/micahflee/torbrowser-launcher/issues/633#issuecomment-1108921204

**Comment by u451f** [comment] 2022-04-25 18:51
PS This is not a support forum but a place to report bugs.

**Comment by davidbaumann** [comment] 2022-12-23 20:34
Duplicate of #633

**Closed by davidbaumann** 2022-12-23 20:34 UTC
