### ISSUE TITLE
Debian repo version sound issues

### ISSUE THREAD

**Issue by kisisten** [micahflee/torbrowser-launcher#324] opened 2018-04-05 18:15 UTC
Hi, I've tried installing the debian version of torbrowser-launcher in stretch and buster but after the installation I get no sound at all. The direct download of  the browser from tor website works fine with sound.
Thanks.

**Comment by desertproject** [comment] 2019-07-19 00:39
Hi, I can confirm this issue using debian buster (10.0) with sid

Seems to be related to #328

**Comment by getreu** [comment] 2019-08-21 06:41
# Workaround for Debian Buster

The version in `develop` supports sound output. 

    sudo apt install torbrowser-launcher
    cd /etc/apparmor.d
    sudo mv torbrowser.Browser.firefox torbrowser.Browser.firefox.orig
    sudo wget https://raw.githubusercontent.com/micahflee/torbrowser-launcher/develop/apparmor/torbrowser.Browser.firefox
    sudo service apparmor restart
    sudo service apparmor status

Expected output

    systemd[1]: Starting Load AppArmor profiles...
    apparmor.systemd[3319]: Restarting AppArmor
    apparmor.systemd[3319]: Reloading AppArmor profiles
    apparmor.systemd[3319]: Ignoring: 'torbrowser.Browser.firefox.orig'
    systemd[1]: Started Load AppArmor profiles.

**Comment by intrigeri** [comment] 2021-05-16 13:50
I'll assume this is/was a Debian specific problem caused by Debian shipping a version of the AppArmor policy that did not include #396 ⇒ not something we should be tracking upstream ⇒ closing.

**Closed by intrigeri** 2021-05-16 13:50 UTC
