### ISSUE TITLE
Tor signature verification fails always

### ISSUE THREAD

**Issue by nirvinm** [micahflee/torbrowser-launcher#263] opened 2017-01-29 11:50 UTC
Tried installing Tor Browser Launcher via GNOME Software and DNF package manager on Fedora. Tor Launcher is getting installed successfully. However I'm not able to download Tor. Everytime I open Tor, installation fails saying "SIGNATURE VERIFICATION FAILED".
Tried all mirrors.
![screenshot from 2017-01-29 17-11-45](https://cloud.githubusercontent.com/assets/7430286/22403761/2d978130-e647-11e6-8c9d-15a475ba2634.png)

**Comment by ge-fa** [comment] 2017-01-29 11:54
Which version of torbrowser-launcher are you using?

**Comment by nirvinm** [comment] 2017-01-29 15:13
Version      :  0.2.6
Release     : 1.fc25
OS: Fedora 25

**Comment by HighCommander4** [comment] 2017-01-29 22:52
I'm seeing this as well, with version 0.1.9 on Debian stable.

**Comment by ge-fa** [comment] 2017-01-29 22:56
@HighCommander4 The Debian bug is reported [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852732). There is a workaround mentioned in the last mail by Holger Levsen.

**Comment by ge-fa** [comment] 2017-01-29 22:56
See #260 as well.

**Comment by fabianHAW** [comment] 2017-01-31 10:36
same problem here. but i can't retrieve the keys: 

`$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu

gpg: refreshing 2 keys from hkp://pgp.mit.edu
gpg: requesting key 63FEE659 from hkp server pgp.mit.edu
gpg: requesting key 93298290 from hkp server pgp.mit.edu
gpgkeys: key 8738A680B84B3031A630F2DB416F061063FEE659 can't be retrieved
gpgkeys: key EF6E286DDA85EA2A4BA7DE684E2C6E8793298290 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0`

any suggestions?

**Comment by eyalroz** [comment] 2017-01-31 16:34
Seeing this on Linux Mint 18.1 64bit:
```
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.4
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Latest version: 6.5
Downloading https://dist.torproject.org/torbrowser/6.5/tor-browser-linux64-6.5_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/6.5/tor-browser-linux64-6.5_en-US.tar.xz
Verifying signature
```
... and then I get the failure message. Happens every time.

**Comment by nirvinm** [comment] 2017-02-01 06:38
@ge-fa Thanks :)
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu`
This fixed the issue in Fedora 25.

**Comment by SirArthurII** [comment] 2017-02-02 01:39
@fabianHAW 
Had the same problem
Debian Jessie 8.7
I am a rookie.
Had problems connecting to Tor since I installed Apparmor.
Disabling Apparmor let me retrieve the keys and install Tor 6.5 eventually.
But I really don't know, if this is save. Ask a pro please.
Now time to config Apparmor properly.

**Comment by fabianHAW** [comment] 2017-02-05 11:26
after some days trying, this workaround worked for me too :) maybe the server (pgp.mit.edu) had some problems. thanks for helping!!

**Comment by micahflee** [comment] 2017-03-13 22:50
This is a duplicate of #260, which is fixed in the latest version of torbrowser-launcher.

**Closed by micahflee** 2017-03-13 22:50 UTC
Labels: duplicate

**Comment by rolfschr** [comment] 2017-03-19 21:39
Hi Micah,

Not sure this is the right place to post & I surely don't want to sound too demanding: Do you mind updating the [non-Trusty ppa packages](https://launchpad.net/~micahflee/+archive/ubuntu/ppa/+packages) to 0.2.7?

Thanks for providing the torbrowser-launcher!

**Comment by CoolSpot** [comment] 2017-04-20 20:36
If pgp.mit.edu is down, one could use
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net`

**Comment by Darkwater409** [comment] 2017-05-28 03:27
I'm having this exact same issue on UbuntuMATE 16.04 LTS. Downloaded from Software Boutique. No idea what the version is.

**Comment by anastiel** [comment] 2017-05-30 23:20
thanks so much running in parrotSec

**Comment by AgileMinion** [comment] 2018-03-01 21:23
muchos gracious .... workaround still works on ubuntu xenial

**Comment by w0298i** [comment] 2018-04-09 01:35
Can confirm that
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu`
works on Xubuntu 4.13.0-38-generic

**Comment by kunaldhariwal** [comment] 2018-09-24 05:06
gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net

This command solved my issue in ParrotSec.

**Comment by fabioeducampos** [comment] 2018-09-29 16:34
This command works for kali 64 gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net 
or that 
gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
I tried both but it did not work 
gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: keyserver refresh failed: Server indicated a failure. 
Help please !  thanks

**Comment by Lanchon** [comment] 2018-10-04 14:13
on linux mint 19 (ubuntu bionic):

```
$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: keyserver refresh failed: Invalid argument
$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net
gpg: refreshing 1 key from hkp://pool.sks-keyservers.net
gpg: keyserver refresh failed: Invalid argument
```

**Comment by Lanchon** [comment] 2018-10-04 14:19
also this... what the hell is wrong??

```
$ sudo add-apt-repository ppa:micahflee/ppa
You are about to add the following PPA:
 This is where I release my Ubuntu software, including Tor Browser Launcher, OnionShare, and PDF Redact Tools.
 More info: https://launchpad.net/~micahflee/+archive/ubuntu/ppa
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.GRpuILjuwc/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7D158F33
gpg: keyserver receive failed: Invalid argument
```

**Comment by fabioeducampos** [comment] 2018-10-05 14:12
Hey dude !
 gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
 when I run this command it returns

gpg:refreshing l key from hkp://pgp.mit.edu 
gpg: keyserver refresh failed: Server indicated  a failure 

This is problem thanks!

**Comment by sh1ng** [comment] 2019-08-14 11:55
gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: keyserver refresh failed: Server indicated a failure

**Comment by winthrom** [comment] 2019-08-25 22:10
workaround fails on kubuntu 16.04

Used this workaround because symtoms were exactly as I saw on this web page.

results:

dad@dad314159:~$ sudo gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: requesting key 93298290 from hkp server pgp.mit.edu
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 21287 new signatures
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 2 new subkeys
gpg: Total number processed: 1
gpg:            new subkeys: 2
gpg:         new signatures: 21287
gpg: no ultimately trusted keys found

dad@dad314159:~$ sudo torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.4
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Latest version: 8.5.4
Downloading https://dist.torproject.org/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz
Verifying signature
Extracting tor-browser-linux64-8.5.4_en-US.tar.xz
Running /home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1472, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1525, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1513, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 537, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1161, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 312, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 329, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 267, in run_task
    self.verify()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 463, in verify
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 271, in run_task
    self.extract()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 503, in extract
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 275, in run_task
    self.run()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
    if not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
exceptions.IOError: [Errno 2] No such file or directory: '/home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'
------------------------------
So I tried:
-------------------------------
dad@dad314159:~$ sudo apt-get install --reinstall --install-suggests tor deb.torproject.org-keyring torbrowser-launcher
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 3 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/1,595 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 1254584 files and directories currently installed.)
Preparing to unpack .../deb.torproject.org-keyring_2018.08.06_all.deb ...
Unpacking deb.torproject.org-keyring (2018.08.06) over (2018.08.06) ...
Preparing to unpack .../tor_0.4.0.5-2~xenial+1_amd64.deb ...
Unpacking tor (0.4.0.5-2~xenial+1) over (0.4.0.5-2~xenial+1) ...
Preparing to unpack .../torbrowser-launcher_0.2.4-1_amd64.deb ...
Unpacking torbrowser-launcher (0.2.4-1) over (0.2.4-1) ...
Processing triggers for man-db (2.7.5-1) ...
/usr/bin/mandb: can't write to /var/cache/man/18381: No space left on device
/usr/bin/mandb: can't create index cache /var/cache/man/18381: No space left on device
Processing triggers for systemd (229-4ubuntu21.22) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up deb.torproject.org-keyring (2018.08.06) ...
Setting up tor (0.4.0.5-2~xenial+1) ...
Setting up torbrowser-launcher (0.2.4-1) ...
dad@dad314159:~$ sudo apt-get build-dep torbrowser-launcher
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
-------------------------
then
-------------------------
dad@dad314159:~$ sudo torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.4
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>                                                                                      
    torbrowser_launcher.main()                                                                                                                   
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main                                                      
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 94, in __init__
    self.run(False)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
    if not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
IOError: [Errno 2] No such file or directory: '/home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

All this started because my installed tor (that worked from ubuntu archives) failed today but had worked a few days ago before I installed low latency kernel. Tor would show for a few seconds on activity bar, then vanish. I purged it and started re-installing. Nojoy. Looked up this version. Nojoy. 

confused....

**Comment by winthrom** [comment] 2019-08-25 22:54
workaround fails on kubuntu 16.04
Used this workaround because symtoms were exactly as I saw on this web page.
results
$ sudo gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: requesting key 93298290 from hkp server pgp.mit.edu
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 21287 new signatures
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 2 new subkeys
gpg: Total number processed: 1
gpg:            new subkeys: 2
gpg:         new signatures: 21287
gpg: no ultimately trusted keys found

$ sudo torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.4
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Latest version: 8.5.4
Downloading https://dist.torproject.org/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/8.5.4/tor-browser-linux64-8.5.4_en-US.tar.xz
Verifying signature
Extracting tor-browser-linux64-8.5.4_en-US.tar.xz
Running /home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1472, in _finishResponse_WAITING
    self._giveUp(Failure(reason))
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1525, in _giveUp
    self._disconnectParser(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1513, in _disconnectParser
    parser.connectionLost(reason)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 537, in connectionLost
    self.response._bodyDataFinished()
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1161, in _bodyDataFinished_CONNECTED
    self._bodyProtocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 312, in connectionLost
    self.all_done(reason)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 329, in response_finished
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 267, in run_task
    self.verify()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 463, in verify
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 271, in run_task
    self.extract()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 503, in extract
    self.run_task()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 275, in run_task
    self.run()
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
    if not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
exceptions.IOError: [Errno 2] No such file or directory: '/home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

So I tried

$ sudo apt-get install --reinstall --install-suggests tor deb.torproject.org-keyring torbrowser-launcher
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 3 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/1,595 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 1254584 files and directories currently installed.)
Preparing to unpack .../deb.torproject.org-keyring_2018.08.06_all.deb ...
Unpacking deb.torproject.org-keyring (2018.08.06) over (2018.08.06) ...
Preparing to unpack .../tor_0.4.0.5-2 xenial+1_amd64.deb ...
Unpacking tor (0.4.0.5-2 xenial+1) over (0.4.0.5-2 xenial+1) ...
Preparing to unpack .../torbrowser-launcher_0.2.4-1_amd64.deb ...
Unpacking torbrowser-launcher (0.2.4-1) over (0.2.4-1) ...
Processing triggers for man-db (2.7.5-1) ...
/usr/bin/mandb: can't write to /var/cache/man/18381: No space left on device
/usr/bin/mandb: can't create index cache /var/cache/man/18381: No space left on device
Processing triggers for systemd (229-4ubuntu21.22) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up deb.torproject.org-keyring (2018.08.06) ...
Setting up tor (0.4.0.5-2 xenial+1) ...
Setting up torbrowser-launcher (0.2.4-1) ...
 $ sudo apt-get build-dep torbrowser-launcher
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded

then

$ sudo torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.4
https://github.com/micahflee/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>                                                                                      
    torbrowser_launcher.main()                                                                                                                   
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main                                                      
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 94, in __init__
    self.run(False)
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
    if not self.check_min_version():
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
    for line in open(self.common.paths['tbb']['versions']).readlines():
IOError: [Errno 2] No such file or directory: '/home/dad/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

All this started because my installed tor (that worked from ubuntu archives) failed today but had worked a few days ago before I installed low latency kernel. Tor would show for a few seconds on activity bar, then vanish. I purged it and started re-installing. Nojoy. Looked up this version. Nojoy. 

confused....**

**Comment by mcmeeking** [comment] 2021-02-12 21:13
Just for anyone who stumbles upon this with the reported issue:

```
gpg --auto-key-locate nodefault,wkd  --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --locate-keys torbrowser@torproject.org
```

**Comment by BarbzYHOOL** [comment] 2022-10-18 21:57
mcmeeking solution is the only one working
