### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by fpauser** [micahflee/torbrowser-launcher#261] opened 2017-01-26 07:50 UTC
OS: Korora 25 (64bit, gnome)
```
$ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.6
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Latest version: 6.5
Downloading https://www.torproject.org/dist/torbrowser/6.5/tor-browser-linux64-6.5_en-US.tar.xz.asc
Downloading https://www.torproject.org/dist/torbrowser/6.5/tor-browser-linux64-6.5_en-US.tar.xz
Verifying signature
Starting download over again
```
The GUI downloads tor and finally gives me a "Signature Verification Failed!"
Starting over does not help.

Doing a manual verification gives:
```
$ gpg --verify tor-browser-linux64-6.5_en-US.tar.xz.asc tor-browser-linux64-6.5_en-US.tar.xz
gpg: Unterschrift vom Di 24 Jan 2017 15:42:49 CET mittels RSA-Schlüssel ID C3C07136
gpg: lookup_hashtable failed: eof
gpg: Korrekte Unterschrift von "Tor Browser Developers (signing key) <torbrowser@torproject.org>"
gpg: lookup_hashtable failed: eof
gpg: WARNUNG: Dieser Schlüssel trägt keine vertrauenswürdige Signatur!
gpg:          Es gibt keinen Hinweis, daß die Signatur wirklich dem vorgeblichen Besitzer gehört.
Haupt-Fingerabdruck  = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
Unter-Fingerabdruck  = A430 0A6B C93C 0877 A445  1486 D148 3FA6 C3C0 7136
```

**Comment by Kajisav** [comment] 2017-01-26 09:03
I believe this is a duplicate of issue #260.

**Comment by micahflee** [comment] 2017-01-27 04:03
Yup, duplicate of #260

**Closed by micahflee** 2017-01-27 04:03 UTC
Labels: duplicate
