### ISSUE TITLE
Tor Browser launcher error

### ISSUE THREAD

**Issue by grioghair** [micahflee/torbrowser-launcher#397] opened 2019-04-02 02:31 UTC
I am getting a “signature verification failed” error when I try to launch the tor browser launcher in subgraph. Is there a way of fixing that?

Steve

**Comment by franciscoguemes** [comment] 2019-04-08 09:25
I am getting the exact same error.

![Tor_failed](https://user-images.githubusercontent.com/36205559/55713432-f2150e00-59f0-11e9-825c-38fcbe2114e9.png)

**Comment by KenzoUme** [comment] 2019-05-04 02:22
Has this been resolved?

**Comment by grioghair** [comment] 2019-05-05 02:03
> Has this been resolved?

No. Tor Browser is the only way of accessing the internet on this system, and until it works there is no way of getting net access to fix anything

**Comment by CryptorClub** [comment] 2019-05-13 07:49
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir" --refresh-keys --keyserver keyserver.ubuntu.com`

**Comment by brunces** [comment] 2019-06-21 14:09
Guys, I was having the same issue, then I decided to turn off my firewall (GUFW) and try to launch Tor Browser again. It worked! Then, I turned on the firewall again and now everything's working normally. I really don't know if the issue was really caused by the firewall, but that was the one and only thing I did and it worked. I hope this is useful somehow.

**Comment by apache-mark** [comment] 2019-07-14 16:02
Hi,

I'm having similar issues with installing Tor Browser (and launcher) on Ubuntu 18.04.
When I first tried the installation I was able to download the software and install it but I was getting an error:

“SIGNATURE VERIFICATION FAILED”. The error code is GENERIC_VERIFY_FAIL.

After updating these keys several times the problem persisted. Now I can not even start the launcher, even after multiple uninstall/reinstalls/restarts.

After doing some digging I came across this article regarding attacks on GPG keyrings that may be causing the issue:

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

There is also a problem with the directory when trying to update the keyrings. I've just read I need to stop trying to update keywrings as many of them maybe corrupt. Hence, I can't recall the exact directory error message but it was something to do with it not being large enough to store the updates (I may be wrong there though). 

I can't find a fix for this anywhere. 

Thanks

**Comment by CryptoClub-io** [comment] 2019-08-05 07:49
Same problem here on Thinkpad running Ubuntu 18.04.2 LTS - time and again the same issue...

**Comment by st1944hu** [comment] 2019-08-20 22:27
![Screenshot from 2019-08-20 15-22-42](https://user-images.githubusercontent.com/12700677/63388851-9b382180-c35e-11e9-8caf-97ed3805b590.png)
Same isssue with new install of Mint 19.2

**Comment by noloader** [comment] 2020-01-23 21:39
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?

**Closed** 2023-01-07 06:49 UTC
