### ISSUE TITLE
Signature Verification failed on Manjaro

### ISSUE THREAD

**Issue by PhantomHydrino** [micahflee/torbrowser-launcher#707] opened 2023-09-25 13:12 UTC
I was trying to install Tor browser but the signature tends to fail, every time after the launcher downloads the browser.

Here is a screenshot

![image](https://github.com/micahflee/torbrowser-launcher/assets/55507011/3c44ffe6-ce38-44d8-b738-d87e031d48e6)

**Comment by techiedesu** [comment] 2023-09-25 13:58
Duplicate of #700

**Closed** 2023-09-26 12:40 UTC
