### ISSUE TITLE
SIGNATURE VERIFICATION FAILED! Error Code: GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by uafredens** [micahflee/torbrowser-launcher#624] opened 2022-02-14 18:09 UTC
Following these guidellines: https://ubuntuhandbook.org/index.php/2021/01/install-tor-tor-browser-ubuntu-20-10-20-04/

I got this error:

![TOR ERROR 2022-02-14 19-03-34](https://user-images.githubusercontent.com/3648035/153921483-4423bb73-b869-4f16-a2d2-241cbf88fbc5.png)

**Comment by crawlserv** [comment] 2022-02-22 13:12
@uafredens I had the same problem and think that this might happen when the TOR service is running but not able to connect to the internet. For me, restarting the TOR service worked (`sudo service tor restart`).

**Comment by nickf12** [comment] 2022-02-23 16:30
Same error following this guidelines: https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/
I have restarted the tor service but the issue is not fixed

**Comment by u451f** [comment] 2022-04-25 18:29
> Same error following this guidelines: https://linuxize.com/post/how-to-install-tor-browser-on-ubuntu-18-04/ I have restarted the tor service but the issue is not fixed

Well, the issue clearly states what your problem could be:

1. You might be under attack,
2. there might be a network problem, 
3. or you may be missing a recently added Tor Browser verification key.

You should try to rule out each of these possible errors to debug. Restarting tor would only fix 2) and only if you requested to install TBB over Tor, for example.

**Comment by davidbaumann** [comment] 2022-12-24 09:20
Duplicate of #633

**Closed** 2023-01-01 19:37 UTC
