### ISSUE TITLE
Running on linux mint 16 fails

### ISSUE THREAD

**Issue by DennisonWilliams** [micahflee/torbrowser-launcher#163] opened 2015-01-15 05:34 UTC
When attempting to launch on linux mint 16 I get the error below.  After it fails it launches a full screen firefox browser that is _not_ connected to Tor.
````
$ ./torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.7
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.0.3
Checked for update within 24 hours, skipping
Latest version of TBB is installed, launching
Launching Tor Browser for Linux in /home/evoltech/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser...

(process:13147): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

Tor Browser exited cleanly.
````

**Comment by micahflee** [comment] 2015-01-19 21:09
This looks like an AppArmor-related issue. Let me take a look.

**Comment by micahflee** [comment] 2015-01-20 22:56
It opens Firefox because of #157. If Firefox is completely closed in the background it should open Tor Browser. I'm still testing in Mint though to see if there are any other issues.

**Comment by micahflee** [comment] 2015-01-20 23:00
Yup confirmed, this is just a duplicate of #157.

**Closed by micahflee** 2015-01-20 23:00 UTC
Labels: bug
