### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by kasongoroger** [micahflee/torbrowser-launcher#701] opened 2023-09-18 10:31 UTC
I'm not able to install torbrowser-launcher on my virtual kali linux machine.
look like the licence key has expired, what to do

![image](https://github.com/micahflee/torbrowser-launcher/assets/54950693/c14ee7e6-91cc-4b56-9021-1aa09bb67eb4)

**Comment by Aeris1One** [comment] 2023-09-18 17:29
Duplicate of #700

**Comment by kasongoroger** [comment] 2023-09-18 21:12
613188FC5BE2176E3D54901E53D989A9E2D47BF:Key expired

**Comment by AsciiWolf** [comment] 2023-09-20 18:54
Thanks for reporting this! This issue is already tracked in #700. Closing this ticket.

**Closed by AsciiWolf** 2023-09-20 18:54 UTC

**Comment by kasongoroger** [comment] 2023-09-23 10:02
I have tried these steps, and it worked perfectly

Here is the link to tor - **https://dist.torproject.org/torbrowser/12.5.4/tor-browser-lisnux64-12.5.4_ALL.tar.xz**

1. **Unzip** the folder
2. locate the Download then **Tor-Browser** then **start-tor-browser.desktop**
3. double click on the launch the file, and **accept whatever message is going to pop-up.**

**you stat-tor-browser icon is going to change and launch your browser.
then you can creat your shortcut on the desktop.**

**Comment by kasongoroger** [comment] 2023-09-23 20:34
I have tried these steps, and it worked perfectly
This has to be done on the Virtual Machine directly and on you local computer if you are not using any virtual machine

Here is the link to tor - https://dist.torproject.org/torbrowser/12.5.4/tor-browser-lisnux64-12.5.4_ALL.tar.xz

Unzip the folder
locate the Download then Tor-Browser then start-tor-browser.desktop
double click on the launch the file, and accept whatever message is going to pop-up.
your stat-tor-browser icon is going to change and launch your browser.
then you can creat your shortcut on the desktop.
